### ISSUE TITLE
Crash due to `unicode` name not existing in Python 3

### ISSUE THREAD

**Issue by telotortium** [kerrickstaley/Chinese-Prestudy#17]
On the most recent version of the addon uploaded to Ankiweb (Updated 2020-11-03), I see the following crash whenever I start up:

```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Chinese Prestudy⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 211, in loadAddons
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/882364911/__init__.py", line 14, in <module>
    import chineseflashcards
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/882364911/chineseflashcards/__init__.py", line 3, in <module>
    import genanki
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/882364911/genanki/__init__.py", line 6, in <module>
    from .model import Model
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/882364911/genanki/model.py", line 3, in <module>
    import pystache
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/882364911/pystache/__init__.py", line 9, in <module>
    from pystache.init import parse, render, Renderer, TemplateSpec
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/882364911/pystache/init.py", line 8, in <module>
    from pystache.parser import parse
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/882364911/pystache/parser.py", line 10, in <module>
    from pystache import defaults
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/882364911/pystache/defaults.py", line 20, in <module>
    from pystache.common import MissingTags
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/882364911/pystache/common.py", line 21, in <module>
    _STRING_TYPES = _get_string_types()
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/882364911/pystache/common.py", line 18, in _get_string_types
    return (unicode, type(u"a".encode('utf-8')))
NameError: name 'unicode' is not defined
```

**Comment by telotortium** [comment]
Caused by defunkt/pystache#209

**Comment by kerrickstaley** [comment]
Resolved, discussion is in https://github.com/kerrickstaley/Chinese-Prestudy/issues/19 .
